package net.cu5tmtp.GregECore.gregstuff.GregMachines.machines.endgame;

import com.gregtechceu.gtceu.GTCEu;
import com.gregtechceu.gtceu.api.capability.recipe.ItemRecipeCapability;
import com.gregtechceu.gtceu.api.data.RotationState;
import com.gregtechceu.gtceu.api.machine.IMachineBlockEntity;
import com.gregtechceu.gtceu.api.machine.MachineDefinition;
import com.gregtechceu.gtceu.api.machine.TickableSubscription;
import com.gregtechceu.gtceu.api.machine.feature.multiblock.IMultiPart;
import com.gregtechceu.gtceu.api.machine.multiblock.PartAbility;
import com.gregtechceu.gtceu.api.machine.multiblock.WorkableElectricMultiblockMachine;
import com.gregtechceu.gtceu.api.pattern.FactoryBlockPattern;
import com.gregtechceu.gtceu.api.pattern.Predicates;
import com.gregtechceu.gtceu.api.recipe.GTRecipe;
import com.gregtechceu.gtceu.common.data.GCYMBlocks;
import com.lowdragmc.lowdraglib.syncdata.annotation.DescSynced;
import com.lowdragmc.lowdraglib.syncdata.annotation.Persisted;
import com.lowdragmc.lowdraglib.syncdata.field.ManagedFieldHolder;
import net.cu5tmtp.GregECore.block.ModBlocks;
import net.cu5tmtp.GregECore.gregstuff.GregMachines.parts.endgame.RealityFractureEnginePartMachine;
import net.cu5tmtp.GregECore.gregstuff.GregMachines.renderer.renderRegistries.GregERenederRegistries;
import net.cu5tmtp.GregECore.gregstuff.GregUtils.notCoreStuff.GregERecipeTypes;
import net.cu5tmtp.GregECore.item.ModItems;
import net.minecraft.ChatFormatting;
import net.minecraft.core.BlockPos;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.block.Blocks;
import net.minecraftforge.items.IItemHandler;
import net.minecraftforge.registries.ForgeRegistries;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static com.gregtechceu.gtceu.api.pattern.Predicates.blocks;
import static com.gregtechceu.gtceu.common.data.models.GTMachineModels.createWorkableCasingMachineModel;
import static net.cu5tmtp.GregECore.gregstuff.GregUtils.GregECore.REGISTRATE;

public class RealityFractureEngine extends WorkableElectricMultiblockMachine{

    public RealityFractureEngine(IMachineBlockEntity holder, Object... args) {
        super(holder, args);
    }

    protected static final ManagedFieldHolder MANAGED_FIELD_HOLDER = new ManagedFieldHolder(
            RealityFractureEngine.class,
            WorkableElectricMultiblockMachine.MANAGED_FIELD_HOLDER);

    @Override
    public ManagedFieldHolder getFieldHolder() {
        return MANAGED_FIELD_HOLDER;
    }

    private TickableSubscription checkingSubscription;

    private final List<IItemHandler> cachedFractureHandler = new ArrayList<>();

    @DescSynced
    public boolean[] areEyesIn = new boolean[3];

    @Persisted
    private boolean portalOpen = false;

    String[] eyeNames = {"Eye of the Red Menace, Ysha'lotha", "Eye of the Purple Stalker, Kal'dora", "Eye of the Green Soldier, Ar'thas"};

    @Override
    public void onStructureFormed() {
        super.onStructureFormed();
        this.cachedFractureHandler.clear();

        for (IMultiPart part : getParts()) {

            if (!(part instanceof RealityFractureEnginePartMachine)) {
                continue;
            }

            var handlerLists = part.getRecipeHandlers();
            for (var handlerList : handlerLists) {
                handlerList.getCapability(ItemRecipeCapability.CAP).stream()
                        .filter(IItemHandler.class::isInstance)
                        .map(IItemHandler.class::cast)
                        .forEach(this.cachedFractureHandler::add);
            }
        }

        if (this.checkingSubscription != null) {
            this.checkingSubscription.unsubscribe();
            this.checkingSubscription = null;
        }
        this.checkingSubscription = this.subscribeServerTick(this::checkWhichEyesAreIn);
    }

    @Override
    public boolean beforeWorking(@Nullable GTRecipe recipe) {
        if (!(areEyesIn[0] && areEyesIn[1] && areEyesIn[2])) {
            return false;
        }
        return super.beforeWorking(recipe);
    }

    @Override
    public boolean onWorking() {
        if (!(areEyesIn[0] && areEyesIn[1] && areEyesIn[2])) {
            return false;
        }
        if (!portalOpen) {
            spawnPortal();
            portalOpen = true;
        }
        return super.onWorking();
    }

    @Override
    public void afterWorking() {
        if (portalOpen) {
            removePortal();
            portalOpen = false;
        }
        super.afterWorking();
    }

    @Override
    public void onStructureInvalid() {
        if (portalOpen) {
            removePortal();
            portalOpen = false;
        }
        super.onStructureInvalid();
    }

    private void checkWhichEyesAreIn() {

        if (getOffsetTimer() % 10 == 0){
            return;
        }

        Arrays.fill(areEyesIn, false);

        for (IItemHandler handler : this.cachedFractureHandler) {
            for (int i = 0; i < handler.getSlots(); i++) {
                ItemStack stack = handler.getStackInSlot(i);
                Item item = stack.getItem();

                if (item == ModItems.GREENEYE.get()) {
                    areEyesIn[0] = true;
                    this.markDirty();
                }
                else if (item == ModItems.REDEYE.get()) {
                    areEyesIn[1] = true;
                    this.markDirty();
                }
                else if (item == ModItems.PURPLEEYE.get()) {
                    areEyesIn[2] = true;
                    this.markDirty();
                }
            }
        }
    }

    private void spawnPortal() {
        if (getLevel() instanceof ServerLevel serverLevel) {
            BlockPos portalPos = getPos()
                    .above(15)
                    .relative(getFrontFacing().getOpposite(), 4);

            if (serverLevel.isEmptyBlock(portalPos)) {
                serverLevel.setBlockAndUpdate(portalPos, ModBlocks.REALITY_PORTAL.getDefaultState());
            }
        }
    }

    private void removePortal() {
        if (getLevel() instanceof ServerLevel serverLevel) {
            BlockPos portalPos = getPos()
                    .above(15)
                    .relative(getFrontFacing().getOpposite(), 4);
            serverLevel.setBlockAndUpdate(portalPos, Blocks.AIR.defaultBlockState());
        }
    }

    public static MachineDefinition REALITYFRACTUREENGINE = REGISTRATE
            .multiblock("realityfractureengine", RealityFractureEngine::new)
            .rotationState(RotationState.NON_Y_AXIS)
            .recipeType(GregERecipeTypes.OPEN_THE_RIFT)
            .appearanceBlock(GCYMBlocks.CASING_HIGH_TEMPERATURE_SMELTING)
            .pattern(definition -> {
                return FactoryBlockPattern.start()
                        .aisle("aaaaaaaaaaaaaaaaaaacccaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabcbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabcbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabcbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabcbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabcbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaacccaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaeeeaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaeeeaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaeeeaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaeeeaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaacccaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabcbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabcbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabcbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabcbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabcbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaacccaaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaacbbbcaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaacaaacaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabcbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaeaaaeaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaafffaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaafffaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaafffaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaebbbeaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaagggaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaagggaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaagggaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaebbbeaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaafffaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaafffaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaafffaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaebbbeaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabcbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaacaaacaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaacbbbcaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaacbbbbbcaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaacaaaaacaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabbabbaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaeaaaaaeaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaafaaafaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaafaaafaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaafaaafaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaebbbbbeaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaagaaagaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaagaaagaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaagaaagaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaebbbbbeaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaafaaafaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaafaaafaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaafaaafaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaebaaabeaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaacaaaaacaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaacbbbbbcaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaacbbbbbcaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaacaaaaacaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaacaaaaacaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaacaaaaacaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaacaaaaacaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaacaaaaacaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaacaaaaacaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaacaaacaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaeaaaaaeaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaafaaafaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaafaaafaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaafaaafaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaebbbbbeaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabahabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaagaiagaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaagaaagaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaagaiagaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabahabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaebbabbeaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaafaaafaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaafaaafaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaafaaafaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaebaaabeaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaacaaacaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaacaaaaacaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaacaaaaacaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaacaaaaacaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaacaaaaacaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaacaaaaacaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaacaaaaacaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaacbbbbbcaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaacbbbbbcaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaacaaaaacaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaeaaaaaeaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaafaaafaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaafaaafaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaafaaafaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaebbbbbeaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaagaaagaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaagaaagaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaagaaagaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaebbbbbeaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaafaaafaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaafaaafaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaafaaafaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaebaaabeaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaacaaaaacaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaabaaaaabaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaacbbbbbcaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaacccccaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabbbbbaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabbbbbaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabbbbbaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabbbbbaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabbbbbaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaacbbbcaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaebbbeaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaafffaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaafffaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaafffaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaebbbeaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabkbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaagggaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaglgaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaagggaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaebbbeaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaafffaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaafffaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaafffaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaebbbeaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaacbbbcaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabbbbbaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabbbbbaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabbbbbaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabbbbbaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabbbbbaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaacccccaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabalabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaacjcaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaeeeaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaeeeaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaeeeaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaeeeaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaacjcaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabalabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabalabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabalabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabalabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabalabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabalabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabalabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaamalamaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaamalamaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaamalamaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaamalamaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabalabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabalabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabalabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabalabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabalabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabalabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabalabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabalabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabalabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabalabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabjbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
                        .aisle("aacccaaaaaaaaaaaaacccccaaaaaaaaaaaaacccaa", "aabcbaaaaaaaaaaaaabbbbbaaaaaaaaaaaaabcbaa", "aabcbaaaaaaaaaaaaabbbbbaaaaaaaaaaaaabcbaa", "aabcbaaaaaaaaaaaaabbbbbaaaaaaaaaaaaabcbaa", "aabcbaaaaaaaaaaaaabbbbbaaaaaaaaaaaaabcbaa", "aabcbaaaaaaaaaaaaabbbbbaaaaaaaaaaaaabcbaa", "aacccaaaaaaaaaaaaabbbbbaaaaaaaaaaaaacccaa", "aaaaaaaaaaaaaaaaaaacjcaaaaaaaaaaaaaaaaaaa", "aaeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaeeeaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaeeeaa", "aaaaaaaaaaaaaaaaaaabbbbaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabgggbaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaeglgeaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabgggbaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaeeeaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaeeeaa", "aaaaaaaaaaaaaaaaaaacjcaaaaaaaaaaaaaaaaaaa", "aacccaaaaaaaaaaaaabbbbbaaaaaaaaaaaaacccaa", "aabcbaaaaaaaaaaaaabbbbbaaaaaaaaaaaaabcbaa", "aabcbaaaaaaaaaaaaabbbbbaaaaaaaaaaaaabcbaa", "aabcbaaaaaaaaaaaaabbbbbaaaaaaaaaaaaabcbaa", "aabcbaaaaaaaaaaaaababbbaaaaaaaaaaaaabcbaa", "aabcbaaaaaaaaaaaaabbbbbaaaaaaaaaaaaabcbaa", "aacccaaaaaaaaaaaaacccccaaaaaaaaaaaaacccaa")
                        .aisle("acbbbcaaaaaaaaaaacbbbbbcaaaaaaaaaaacbbbca", "abaaabaaabbbbaaaabaaaaabaaaabbbbaaabaaaba", "abbbbbabbbmmbbbaabaaaaabaabbbmmbbbabbbbba", "abaaabbbbbbbbbbbbbaaaaabbbbbbbbbbbbbaaaba", "abaaabbbbaaaabbbbbaaaaabbbbbaaaabbbbaaaba", "abaaabbaaaaaaaabbbaaaaabbbaaaaaaaabbaaaba", "acaaacaaaaaaaaaaabaaaaabaaaaaaaaaaacaaaca", "aabcbaaaaaaaaaaaaacbbbcaaaaaaaaaaaaabcbaa", "aebbbeaaaaaaaaaaaaabjbaaaaaaaaaaaaaebbbea", "aafffaaaaaaaaaaaaaafffaaaaaaaaaaaaaafffaa", "aafffaaaaaaaaaaaaaafffaaaaaaaaaaaaaafffaa", "aafffaaaaaaaaaaaaaafffaaaaaaaaaaaaaafffaa", "aebbbeaaaaaaaaaaaaabbbaaaaaaaaaaaaaebbbea", "aabbbaaaaaaaaaaaaabaaabbaaaaaaaaaaaabbbaa", "aagggaaaaaaaaaaaabaaaaabaaaaaaaaaaaagggaa", "aagggaaaaaaaaaaaaeaaaaaeaaaaaaaaaaaagggaa", "aagggaaaaaaaaaaaabaaaaabaaaaaaaaaaaagggaa", "aabbbaaaaaaaaaaaaabaaabaaaaaaaaaaaaabbbaa", "aebbbeaaaaaaaaaaaaabbbaaaaaaaaaaaaaebbbea", "aafffaaaaaaaaaaaaaafffaaaaaaaaaaaaaafffaa", "aafffaaaaaaaaaaaaaafffaaaaaaaaaaaaaafffaa", "aafffaaaaaaaaaaaaaafffaaaaaaaaaaaaaafffaa", "aebbbeaaaaaaaaaaaaabbbaaaaaaaaaaaaaebbbea", "aabcbaaaaaaaaaaaaacbbbcaaaaaaaaaaaaabcbaa", "acaaacaaaaaaaaaaabaaaaabaaaaaaaaaaacaaaca", "abaaabbaaaaaaaabbbaaaaabbbaaaaaaaabbaaaba", "abaaabbbbaaaabbbbbaaaaabbbbbaaaabbbbaaaba", "abaaabbbbbbbbbbbbbaaaaabbbbbbbbbbbbbaaaba", "abaaababbbmmbbbaabbaaaabaabbbmmbbbabbbbba", "abaaabaaabbbbaaaabaaaaabaaaabbbbaaabaaaba", "acbbbcaaaaaaaaaaacbbbbbcaaaaaaaaaaacbbbca")
                        .aisle("cbbbbcaaabbbbaaaacbbbbbcaaaabbbbaaacbbbbc", "baaaababbaaaabbaabaanaabaabbaaaabbabaaaab", "bbbbbbbaaaaaaaabbbaanaabbbaaaaaaaabbbbbbb", "baaaabaaaaaaaaaaabaanaabaaaaaaaaaaabaaaab", "baaaabaaabbbbaaaabaanaabaaaabbbbaaabaaaab", "baaaababbaaaabbaabaanaabaabbaaaabbabaaaab", "caaaabcaaaaaaaabbbaanaabbbaaaaaaaabcaaaac", "abbbbbaaaaaaaaaaacbbbbbcaaaaaaaaaaabbbbba", "ebaaabeaaaaaaaaaaabaaabaaaaaaaaaaaebaaabe", "afbbbfaaaaaaaaaaaafbbbfaaaaaaaaaaaafbbbfa", "afaaafaaaaaaaaaaaafaaafaaaaaaaaaaaafaaafa", "afaaafaaaaaaaaaaaafaaafaaaaaaaaaaaafaaafa", "ebbbbbeaaaaaaaaaaabbbbbaaaaaaaaaaaebbbbbe", "abaaabaaaaaaaaaaabaaaaabaaaaaaaaaaabaaaba", "agaaagaaaaaaaaaaagaaaaagaaaaaaaaaaagaaaga", "agaaagaaaaaaaaaaagaaaaagaaaaaaaaaaagaaaga", "agaaagaaaaaaaaaaagaaaaagaaaaaaaaaaagaaaga", "abaaabaaaaaaaaaaabaaaaabaaaaaaaaaaabaaaba", "ebbbbbeaaaaaaaaaaabbbbbaaaaaaaaaaaebbbbbe", "afaaafaaaaaaaaaaaafaaafaaaaaaaaaaaafaaafa", "afaaafaaaaaaaaaaaafaaafaaaaaaaaaaaafaaafa", "afaaafaaaaaaaaaaaafaaafaaaaaaaaaaaafaaafa", "ebaaabeaaaaaaaaaaabaaabaaaaaaaaaaaebaaabe", "abbbbbaaaaaaaaaaacbbbbbcaaaaaaaaaaabbbbba", "caaaaacaaaaaaaabbbaanaabbbaaaaaaaabcaaaac", "baaaababbaaaabbaabaanaabaabbaaaabbabaaaab", "baaaabaaabbbbaaaabaanaabaaaabbbbaaabaaaab", "baaaabaaaaaaaaaaabaanaabaaaaaaaaaaabaaaab", "baaaabbaaaaaaaabbbaanaabbbaaaaaaaabbbbbbb", "baaaababbaaaabbaabaanaabaabbaaaabbabaaaab", "cbbbbcaaabbbbaaaacbbbbbcaaaabbbbaaacbbbbc")
                        .aisle("cbbbbcaaajjjjaaaacbbbbbcaaaajjjjaaacbbbbc", "caaaabajjaaaajjaabannnabaajjaaaajjabaaaac", "cbbbbbjaallllaajjbannnabjjaallllaajbbbbbc", "caaaaballaaaallaabannnabaallaaaallabaaaac", "caaaablaajjjjaallbannnabllaajjjjaalbaaaac", "caaaabajjaaaajjaabannnabaajjaaaajjabaaaac", "caaaabjaaaaaaaajjbannnabjjaaaaaaaajcaaaac", "acbbbjaaaaaaaaaaajbbbbbjaaaaaaaaaaajbbbca", "ebaaabeaaaaaaaaaaajaaajaaaaaaaaaaaebaaabe", "afbbbfaaaaaaaaaaaafbbbfaaaaaaaaaaaafbbbfa", "afaaafaaaaaaaaaaaafaaafaaaaaaaaaaaafaaafa", "afaaafaaaaaaaaaaaafaaafaaaaaaaaaaaafaaafa", "ebbbbbeaaaaaaaaaaabbbbbaaaaaaaaaaaebbbbbe", "abahakaaaaaaaaaaabaaaaabaaaaaaaaaaakahaba", "agaiagaaaaaaaaaaagaaaaagaaaaaaaaaaagaiaga", "agaaalaaaaaaaaaaalaaaaalaaaaaaaaaaalaaaga", "agaiagaaaaaaaaaaagaaaaagaaaaaaaaaaagaiaga", "abahabaaaaaaaaaaabaaaaabaaaaaaaaaaabahaba", "ebbbbbeaaaaaaaaaaabbbbbaaaaaaaaaaaebbbbbe", "afaaafaaaaaaaaaaaafaaafaaaaaaaaaaaafaaafa", "afaaafaaaaaaaaaaaafaaafaaaaaaaaaaaafaaafa", "afaaafaaaaaaaaaaaafaaafaaaaaaaaaaaafaaafa", "ebaaabeaaaaaaaaaaabaaabaaaaaaaaaaaebaaabe", "acbbbbaaaaaaaaaaajbbbbbjaaaaaaaaaaajbbbca", "caaaaajaaaaaaaajjbannnabjjaaaaaaaajcaaaac", "caaaabajjaaaajjaabannnabaajjaaaajjabaaaac", "caaaablaajjjjaallbannnabllaajjjjaalbaaaac", "caaaaballaaaallaabannnabaallaaaallabaaaac", "caaaabjaallllaajjbannnabjjaallllaajbbbbbc", "caaaabajjaaaajjaabannnabaajjaaaajjabaaaac", "cbbbbcaaajjjjaaaacbbbbbcaaaajjjjaaacbbbbc")
                        .aisle("cbbbbcaaabbbbaaaacbbbbbcaaaabbbbaaacbbbbc", "baaaababbaaaabbaabaanaabaabbaaaabbabaaaab", "bbbbbbbaaaaaaaabbbaanaabbbaaaaaaaabbbbbbb", "baaaabaaaaaaaaaaabaanaabaaaaaaaaaaabaaaab", "baaaabaaabbbbaaaabaanaabaaaabbbbaaabaaaab", "baaaababbaaaabbaabaanaabaabbaaaabbabaaaab", "caaaabcaaaaaaaabbbaanaabbbaaaaaaaabcaaaac", "abbbbbaaaaaaaaaaacbbbbbcaaaaaaaaaaabbbbba", "ebaaabeaaaaaaaaaaabaaabaaaaaaaaaaaebaaabe", "afbbbfaaaaaaaaaaaafbbbfaaaaaaaaaaaafbbbfa", "afaaafaaaaaaaaaaaafaaafaaaaaaaaaaaafaaafa", "afaaafaaaaaaaaaaaafaaafaaaaaaaaaaaafaaafa", "ebbbbbeaaaaaaaaaaabbbbbaaaaaaaaaaaebbbbbe", "abaaabaaaaaaaaaaabaaaaabaaaaaaaaaaabaaaba", "agaaagaaaaaaaaaaagaaaaagaaaaaaaaaaagaaaga", "agaaagaaaaaaaaaaagaaaaagaaaaaaaaaaagaaaga", "agaaagaaaaaaaaaaagaaaaagaaaaaaaaaaagaaaga", "abaaabaaaaaaaaaaabaaaaabaaaaaaaaaaabaaaba", "ebbbbbeaaaaaaaaaaabbbbbaaaaaaaaaaaebbbbbe", "afaaafaaaaaaaaaaaafaaafaaaaaaaaaaaafaaafa", "afaaafaaaaaaaaaaaafaaafaaaaaaaaaaaafaaafa", "afaaafaaaaaaaaaaaafaaafaaaaaaaaaaaafaaafa", "ebaaabeaaaaaaaaaaabaaabaaaaaaaaaaaebaaabe", "abbbbbaaaaaaaaaaacbbbbbcaaaaaaaaaaabbbbba", "caaaaacaaaaaaaabbbaanaabbbaaaaaaaabcaaaac", "baaaababbaaaabbaabaanaabaabbaaaabbabaaaab", "baaaabaaabbbbaaaabaanaabaaaabbbbaaabaaaab", "baaaabaaaaaaaaaaabaanaabaaaaaaaaaaabaaaab", "baaaabbaaaaaaaabbbaanaabbbaaaaaaaabbbbbbb", "baaaababbaaaabbaabaanaabaabbaaaabbabaaaab", "cbbbbcaaabbbbaaaacbbbbbcaaaabbbbaaacbbbbc")
                        .aisle("acbbbcaaaaaaaaaaacbbbbbcaaaaaaaaaaacbbbca", "abaaabaaabbbbaaaabaaaaabaaaabbbbaaabaaaba", "abbbbbabbbmmbbbaabaaaaabaabbbmmbbbabbbbba", "abaaabbbbbbbbbbbbbaaaaabbbbbbbbbbbbbaaaba", "abaaabbbbaaaabbbbbaaaaabbbbbaaaabbbbaaaba", "abaaabbaaaaaaaabbbaaaaabbbaaaaaaaabbaaaba", "acaaacaaaaaaaaaaabaaaaabaaaaaaaaaaacaaaca", "aabcbaaaaaaaaaaaaacbbbcaaaaaaaaaaaaabcbaa", "aebbbeaaaaaaaaaaaaabjbaaaaaaaaaaaaaebbbea", "aafffaaaaaaaaaaaaaafffaaaaaaaaaaaaaafffaa", "aafffaaaaaaaaaaaaaafffaaaaaaaaaaaaaafffaa", "aafffaaaaaaaaaaaaaafffaaaaaaaaaaaaaafffaa", "aebbbeaaaaaaaaaaaaabbbaaaaaaaaaaaaaebbbea", "aabbbaaaaaaaaaaaaabaaabaaaaaaaaaaaaabbbaa", "aagggaaaaaaaaaaaabaaaaabaaaaaaaaaaaagggaa", "aagggaaaaaaaaaaaaeaaaaaeaaaaaaaaaaaagggaa", "aagggaaaaaaaaaaaabaaaaabaaaaaaaaaaaagggaa", "aabbbaaaaaaaaaaaaabaaabaaaaaaaaaaaaabbbaa", "aebbbeaaaaaaaaaaaaabbbaaaaaaaaaaaaaebbbea", "aafffaaaaaaaaaaaaaafffaaaaaaaaaaaaaafffaa", "aafffaaaaaaaaaaaaaafffaaaaaaaaaaaaaafffaa", "aafffaaaaaaaaaaaaaafffaaaaaaaaaaaaaafffaa", "aebbbeaaaaaaaaaaaaabbbaaaaaaaaaaaaaebbbea", "aabcbaaaaaaaaaaaaacbbbcaaaaaaaaaaaaabcbaa", "acaaacaaaaaaaaaaabaaaaabaaaaaaaaaaacaaaca", "abaaabbaaaaaaaabbbaaaaabbbaaaaaaaabbaaaba", "abaaabbbbaaaabbbbbaaaaabbbbbaaaabbbbaaaba", "abaaabbbbbbbbbbbbbaaaaabbbbbbbbbbbbbaaaba", "abaaababbbmmbbbaabaaaaabaabbbmmbbbabbbbba", "abaaabaaabbbbaaaabaaaaabaaaabbbbaaabaaaba", "acbbbcaaaaaaaaaaacbbbbbcaaaaaaaaaaacbbbca")
                        .aisle("aacccaaaaaaaaaaaaacbbbcaaaaaaaaaaaaacccaa", "aabcbaaaaaaaaaaaaacaaacaaaaaaaaaaaaabcbaa", "aabcbaaaaaaaaaaaaacaaacaaaaaaaaaaaaabcbaa", "aabcbaaaaaaaaaaaaacaaacaaaaaaaaaaaaabcbaa", "aabcbaaaaaaaaaaaaacaaacaaaaaaaaaaaaabcbaa", "aabcbaaaaaaaaaaaaacaaacaaaaaaaaaaaaabcbaa", "aacccaaaaaaaaaaaaacaaacaaaaaaaaaaaaacccaa", "aaaaaaaaaaaaaaaaaaacccaaaaaaaaaaaaaaaaaaa", "aaeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaeeeaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaeeeaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaeaaaeaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaabaaabaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaeeeaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaeeeaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaeeeaa", "aaaaaaaaaaaaaaaaaaacccaaaaaaaaaaaaaaaaaaa", "aacccaaaaaaaaaaaaacaaacaaaaaaaaaaaaacccaa", "aabcbaaaaaaaaaaaaacaaacaaaaaaaaaaaaabcbaa", "aabcbaaaaaaaaaaaaacaaacaaaaaaaaaaaaabcbaa", "aabcbaaaaaaaaaaaaacaaacaaaaaaaaaaaaabcbaa", "aabcbaaaaaaaaaaaaacaaacaaaaaaaaaaaaabcbaa", "aabcbaaaaaaaaaaaaacaaacaaaaaaaaaaaaabcbaa", "aacccaaaaaaaaaaaaacbbbcaaaaaaaaaaaaacccaa")
                        .aisle("aaaaaaaaaaaaaaaaaaapopaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabmbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabmbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabmbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabmbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabmbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabmbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabmbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabmbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaacccaaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaababaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaababaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaababaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaababaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaababaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaababaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaababaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaababaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaababaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaababaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaababaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
                        .aisle("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaabbbaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
                        .where("a", Predicates.any())
                        .where("b", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:atomic_casing"))))
                        .where("c", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:high_temperature_smelting_casing"))))
                        .where("e", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:large_scale_assembler_casing"))))
                        .where("f", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gregecore:awakened_draconium_coil"))))
                        .where("g", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:cleanroom_glass"))))
                        .where("h", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:steel_gearbox"))))
                        .where("i", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("minecraft:iron_bars"))))
                        .where("j", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:industrial_steam_casing"))))
                        .where("k", Predicates.abilities(RealityFractureEnginePartMachine.getPartAbility()).setMaxGlobalLimited(3).setPreviewCount(3))
                        .where("l", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:fusion_coil"))))
                        .where("m", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:fusion_glass"))))
                        .where("n", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:superconducting_coil"))))
                        .where("o", Predicates.controller(blocks(definition.getBlock())))
                        .where('p', Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:high_temperature_smelting_casing")))
                                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(1).setPreviewCount(1))
                                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(1).setPreviewCount(1)))
                        .build();
            })
            .model(createWorkableCasingMachineModel(
                    GTCEu.id("block/casings/gcym/high_temperature_smelting_casing"),
                    GTCEu.id("block/multiblock/fusion_reactor"))
                    .andThen(b -> b.addDynamicRenderer(GregERenederRegistries::createRealityEngineRender)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Abilities: Rift Opening").withStyle(style -> style.withColor(0xFFD700)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Make the 3 following items:").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("Eye of the Red Menace, Ysha'lotha").withStyle(style -> style.withColor(0xC41E3A)))
            .tooltips(Component.literal("Eye of the Purple Stalker, Kal'dora").withStyle(style -> style.withColor(0x702963)))
            .tooltips(Component.literal("Eye of the Green Soldier, Ar'thas").withStyle(style -> style.withColor(0x228B22)))
            .tooltips(Component.literal("And insert them into Reality Fracture Holders. Then you can open the rift with Infinity Catalyst.").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Do not enter without full infinity gear. The dimension you are stepping into will kill you without it.").withStyle(style -> style.withColor(0x90EE90)))
            .register();

    @Override
    public void addDisplayText(@NotNull List<Component> textList) {

        for (int i = 0; i < areEyesIn.length; i++) {
            ChatFormatting color = areEyesIn[i] ? ChatFormatting.GREEN : ChatFormatting.RED;
            String status = areEyesIn[i] ? " is present." : " is missing.";

            textList.add(Component.literal(eyeNames[i] + status).withStyle(color));
        }

        super.addDisplayText(textList);
    }

    public static void init() {
    }
}
