package net.cu5tmtp.GregECore.gregstuff.GregMachines.machines.uhvmulti;

import com.gregtechceu.gtceu.GTCEu;
import com.gregtechceu.gtceu.api.data.RotationState;
import com.gregtechceu.gtceu.api.machine.MachineDefinition;
import com.gregtechceu.gtceu.api.machine.multiblock.PartAbility;
import com.gregtechceu.gtceu.api.pattern.FactoryBlockPattern;
import com.gregtechceu.gtceu.api.pattern.Predicates;
import com.gregtechceu.gtceu.api.recipe.GTRecipeType;
import com.gregtechceu.gtceu.common.data.GCYMBlocks;
import com.gregtechceu.gtceu.common.data.GTBlocks;
import com.gregtechceu.gtceu.common.data.GTRecipeModifiers;
import com.gregtechceu.gtceu.common.data.GTRecipeTypes;
import net.cu5tmtp.GregECore.gregstuff.GregMachines.parts.threadParts.ThreadT3PartMachine;
import net.minecraft.ChatFormatting;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraftforge.registries.ForgeRegistries;

import static net.cu5tmtp.GregECore.gregstuff.GregUtils.GregECore.REGISTRATE;

public class UHVMultiRegistry {

    public static final MachineDefinition GIANT_SOLIDIFICATION = REGISTRATE
            .multiblock("giant_solidification", ThreadedMultiblockBase::new)
            .rotationState(RotationState.ALL)
            .recipeTypes(GTRecipeTypes.FLUID_SOLIDFICATION_RECIPES)
            .recipeModifiers(GTRecipeModifiers.OC_PERFECT, GTRecipeModifiers.PARALLEL_HATCH)
            .appearanceBlock(GCYMBlocks.CASING_WATERTIGHT)
            .pattern(definition -> FactoryBlockPattern.start()
                    .aisle("aaaaa", "abbba", "abbba", "abbba", "aaaaa")
                    .aisle("accca", "bdedb", "bdedb", "bdddb", "accca")
                    .aisle("accca", "bfdfb", "bgegb", "bdddb", "accca")
                    .aisle("accca", "bdddb", "beeeb", "bdddb", "accca")
                    .aisle("accca", "bdddb", "bdedb", "bdddb", "accca")
                    .aisle("accca", "bfdfb", "bgegb", "bdddb", "accca")
                    .aisle("accca", "bdddb", "beeeb", "bdddb", "accca")
                    .aisle("accca", "bdddb", "bdedb", "bdddb", "accca")
                    .aisle("accca", "bfdfb", "bgegb", "bdddb", "accca")
                    .aisle("accca", "bdddb", "beeeb", "bdddb", "accca")
                    .aisle("aahaa", "abbba", "abbba", "abbba", "aaaaa")
                    .where("a", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:watertight_casing")))
                            .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2).setPreviewCount(2))
                            .or(Predicates.abilities(PartAbility.MAINTENANCE).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(ThreadT3PartMachine.getPartAbility()).setMaxGlobalLimited(1).setPreviewCount(1)))
                    .where("b", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:tempered_glass"))))
                    .where("c", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:solid_machine_casing"))))
                    .where("d", Predicates.any())
                    .where("e", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:steel_pipe_casing"))))
                    .where("f", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:clean_machine_casing"))))
                    .where("g", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:stainless_steel_gearbox"))))
                    .where('h', Predicates.controller(Predicates.blocks(definition.get())))
                    .build()
            )
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Abilities: Perfect Overclock, Parallel Hatch and Threading").withStyle(style -> style.withColor(0xFFD700)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Created for ultra-fast fluid solidifying.").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Available Recipe Type: Fluid Solidifier").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("Accepts Threading Core T3.").withStyle(ChatFormatting.LIGHT_PURPLE))
            .workableCasingModel(
                    GTCEu.id("block/casings/gcym/watertight_casing"),
                    GTCEu.id("block/multiblock/distillation_tower")
            )
            .register();

    public static final MachineDefinition GIANT_CHEMICAL_BATH = REGISTRATE
            .multiblock("giant_chemical_bath", ThreadedMultiblockBase::new)
            .rotationState(RotationState.ALL)
            .recipeTypes(GTRecipeTypes.CHEMICAL_BATH_RECIPES)
            .recipeModifiers(GTRecipeModifiers.OC_PERFECT, GTRecipeModifiers.PARALLEL_HATCH)
            .appearanceBlock(GCYMBlocks.CASING_WATERTIGHT)
            .pattern(definition -> FactoryBlockPattern.start()
                    .aisle("aaaaaaa", "aaaaaaa", "aaaaaaa", "aaaaaaa", "aaaaaaa")
                    .aisle("aaaaaaa", "abbbbba", "accccca", "accccca", "addddda")
                    .aisle("aaaaaaa", "abcccba", "accccca", "accccca", "addddda")
                    .aisle("aaaaaaa", "abcccba", "accccca", "accccca", "addddda")
                    .aisle("aaaaaaa", "abcccba", "accccca", "accccca", "addddda")
                    .aisle("aaaaaaa", "abcccba", "accccca", "accccca", "addddda")
                    .aisle("aaaaaaa", "abcccba", "accccca", "accccca", "addddda")
                    .aisle("aaaaaaa", "abbbbba", "accccca", "accccca", "addddda")
                    .aisle("aaahaaa", "aaaaaaa", "aaaaaaa", "aaaaaaa", "aaaaaaa")
                    .where("a", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:watertight_casing")))
                            .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2).setPreviewCount(2))
                            .or(Predicates.abilities(PartAbility.MAINTENANCE).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(ThreadT3PartMachine.getPartAbility()).setMaxGlobalLimited(1).setPreviewCount(1)))
                    .where("b", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:titanium_pipe_casing"))))
                    .where("c", Predicates.any())
                    .where("d", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:tempered_glass"))))
                    .where('h', Predicates.controller(Predicates.blocks(definition.get())))
                    .build()
            )
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Abilities: Perfect Overclock, Parallel Hatch and Threading").withStyle(style -> style.withColor(0xFFD700)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Created for ultra-fast chemical bathing.").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Available Recipe Type: Chemical Bath").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("Accepts Threading Core T3.").withStyle(ChatFormatting.LIGHT_PURPLE))
            .workableCasingModel(
                    GTCEu.id("block/casings/gcym/watertight_casing"),
                    GTCEu.id("block/multiblock/distillation_tower")
            )
            .register();

    public static final MachineDefinition GIANT_EXTRACTION = REGISTRATE
            .multiblock("giant_extraction", ThreadedMultiblockBase::new)
            .rotationState(RotationState.ALL)
            .recipeTypes(GTRecipeTypes.EXTRACTOR_RECIPES, GTRecipeTypes.CANNER_RECIPES)
            .recipeModifiers(GTRecipeModifiers.OC_PERFECT, GTRecipeModifiers.PARALLEL_HATCH)
            .appearanceBlock(GCYMBlocks.CASING_WATERTIGHT)
            .pattern(definition -> FactoryBlockPattern.start()
                    .aisle("aaaabbbaaaa", "aaaabcbaaaa", "aaaabcbaaaa", "aaaabcbaaaa", "aaaabcbaaaa", "aaaabcbaaaa", "aaaabbbaaaa", "aaaaaaaaaaa")
                    .aisle("aaabbbbbaaa", "dddbaaabddd", "aaabaaabaaa", "aaabaaabaaa", "aaabaaabaaa", "aaabaaabaaa", "aaabaaabaaa", "aaaabbbaaaa")
                    .aisle("dddbbbbbddd", "eeeeafagggg", "dddcafacddd", "aaacafacaaa", "aaacafacaaa", "aaacafacaaa", "aaabaaabaaa", "aaaabbbaaaa")
                    .aisle("aaabbbbbaaa", "dddbaaabddd", "aaabaaabaaa", "aaabaaabaaa", "aaabaaabaaa", "aaabaaabaaa", "aaabaaabaaa", "aaaabbbaaaa")
                    .aisle("aaaabhbaaaa", "aaaabcbaaaa", "aaaabcbaaaa", "aaaabcbaaaa", "aaaabcbaaaa", "aaaabcbaaaa", "aaaabbbaaaa", "aaaaaaaaaaa")
                    .where("a", Predicates.any())
                    .where("b", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:watertight_casing"))))
                    .where("c", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:heatproof_machine_casing"))))
                    .where("d", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:nonconducting_casing")))
                            .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2).setPreviewCount(2))
                            .or(Predicates.abilities(PartAbility.MAINTENANCE).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(ThreadT3PartMachine.getPartAbility()).setMaxGlobalLimited(1).setPreviewCount(1)))
                    .where("e", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:ptfe_pipe_casing"))))
                    .where("f", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("kubejs:heatingel"))))
                    .where("g", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:stainless_steel_gearbox"))))
                    .where('h', Predicates.controller(Predicates.blocks(definition.get())))
                    .build()
            )
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Abilities: Perfect Overclock, Parallel Hatch and Threading").withStyle(style -> style.withColor(0xFFD700)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Created for ultra-fast extracting and canning.").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Available Recipe Types: Extractor, Canner").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("Accepts Threading Core T3.").withStyle(ChatFormatting.LIGHT_PURPLE))
            .workableCasingModel(
                    GTCEu.id("block/casings/gcym/watertight_casing"),
                    GTCEu.id("block/multiblock/distillation_tower")
            )
            .register();

    public static final MachineDefinition GIANT_CRYSTALLIZATION = REGISTRATE
            .multiblock("giant_crystallization", ThreadedMultiblockBase::new)
            .rotationState(RotationState.ALL)
            .recipeTypes(GTRecipeTypes.AUTOCLAVE_RECIPES)
            .recipeModifiers(GTRecipeModifiers.OC_PERFECT, GTRecipeModifiers.PARALLEL_HATCH)
            .appearanceBlock(GCYMBlocks.CASING_WATERTIGHT)
            .pattern(definition -> FactoryBlockPattern.start()
                    .aisle("aaaaaaa", "abbbbba", "abbbbba", "abbbbba", "aaaaaaa", "abbbbba", "aaaaaaa")
                    .aisle("accccca", "bdddddb", "bdddddb", "bdddddb", "aeeeeea", "bdddddb", "accccca")
                    .aisle("afffffa", "bdddddb", "bdddddb", "bdddddb", "aeeeeea", "bdddddb", "accccca")
                    .aisle("accccca", "bdddddb", "bdddddb", "bdddddb", "aeeeeea", "bdddddb", "accccca")
                    .aisle("afffffa", "bdddddb", "bdddddb", "bdddddb", "aeeeeea", "bdddddb", "accccca")
                    .aisle("accccca", "bdddddb", "bdddddb", "bdddddb", "aeeeeea", "bdddddb", "accccca")
                    .aisle("aaahaaa", "abbbbba", "abbbbba", "abbbbba", "aaaaaaa", "abbbbba", "aaaaaaa")
                    .where("a", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:watertight_casing")))
                            .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2).setPreviewCount(2))
                            .or(Predicates.abilities(PartAbility.MAINTENANCE).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(ThreadT3PartMachine.getPartAbility()).setMaxGlobalLimited(1).setPreviewCount(1)))
                    .where("b", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:tempered_glass"))))
                    .where("c", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:solid_machine_casing"))))
                    .where("d", Predicates.any())
                    .where("e", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:steel_gearbox"))))
                    .where("f", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:steel_pipe_casing"))))
                    .where('h', Predicates.controller(Predicates.blocks(definition.get())))
                    .build()
            )
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Abilities: Perfect Overclock, Parallel Hatch and Threading").withStyle(style -> style.withColor(0xFFD700)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Created for ultra-fast crystallizing.").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Available Recipe Type: Crystallizer").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("Accepts Threading Core T3.").withStyle(ChatFormatting.LIGHT_PURPLE))
            .workableCasingModel(
                    GTCEu.id("block/casings/gcym/watertight_casing"),
                    GTCEu.id("block/multiblock/distillation_tower")
            )
            .register();

    public static final MachineDefinition GIANT_DISTILLATION = REGISTRATE
            .multiblock("giant_distillation", ThreadedMultiblockBase::new)
            .rotationState(RotationState.ALL)
            .recipeTypes(GTRecipeTypes.DISTILLATION_RECIPES, GTRecipeTypes.DISTILLERY_RECIPES)
            .recipeModifiers(GTRecipeModifiers.OC_PERFECT, GTRecipeModifiers.PARALLEL_HATCH)
            .appearanceBlock(GCYMBlocks.CASING_WATERTIGHT)
            .pattern(definition -> FactoryBlockPattern.start()
                    .aisle("aaaaaaa", "bbdbdbb", "bbdbdbb", "bbdbdbb", "bbdbdbb", "bbdbdbb", "baaaaab", "bbdbdbb", "bbdbdbb", "bbdbdbb", "bbdbdbb", "bbdbdbb", "baaaaab", "bbdbdbb", "bbdbdbb", "bbdbdbb", "bbdbdbb")
                    .aisle("aaaaaaa", "bbcccbb", "bbcccbb", "bbcccbb", "bbcccbb", "bbcccbb", "abcccba", "bbcccbb", "bbcccbb", "bbcccbb", "bbcccbb", "bbcccbb", "abcccba", "bbcccbb", "bbcccbb", "bbcccbb", "bbbbbbb")
                    .aisle("aaaaaaa", "bcbbbcb", "bcbbbcb", "bcbbbcb", "bcbbbcb", "bcbbbcb", "acbbbca", "bcbbbcb", "bcbbbcb", "bcbbbcb", "bcbbbcb", "bcbbbcb", "acbbbca", "bcbbbcb", "bcbbbcb", "bcbbbcb", "bbcccbb")
                    .aisle("aaaaaaa", "bcbbbcb", "bcbbbcb", "bcbbbcb", "bcbbbcb", "bcbbbcb", "acbbbca", "bcbbbcb", "bcbbbcb", "bcbbbcb", "bcbbbcb", "bcbbbcb", "acbbbca", "bcbbbcb", "bcbbbcb", "bcbbbcb", "bbcecbb")
                    .aisle("aaaaaaa", "bcbbbcb", "bcbbbcb", "bcbbbcb", "bcbbbcb", "bcbbbcb", "acbbbca", "bcbbbcb", "bcbbbcb", "bcbbbcb", "bcbbbcb", "bcbbbcb", "acbbbca", "bcbbbcb", "bcbbbcb", "bcbbbcb", "bbcccbb")
                    .aisle("aaaaaaa", "bbchcbb", "bbcccbb", "bbcccbb", "bbcccbb", "bbcccbb", "abcccba", "bbcccbb", "bbcccbb", "bbcccbb", "bbcccbb", "bbcccbb", "abcccba", "bbcccbb", "bbcccbb", "bbcccbb", "bbbbbbb")
                    .aisle("aaaaaaa", "bbbbbbb", "bbbbbbb", "bbbbbbb", "bbbbbbb", "bbbbbbb", "baaaaab", "bbbbbbb", "bbbbbbb", "bbbbbbb", "bbbbbbb", "bbbbbbb", "baaaaab", "bbbbbbb", "bbbbbbb", "bbbbbbb", "bbbbbbb")
                    .where("a", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:solid_machine_casing"))))
                    .where("b", Predicates.any())
                    .where("c", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:watertight_casing")))
                            .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2).setPreviewCount(2))
                            .or(Predicates.abilities(PartAbility.MAINTENANCE).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(ThreadT3PartMachine.getPartAbility()).setMaxGlobalLimited(1).setPreviewCount(1)))
                    .where("d", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:hsse_frame"))))
                    .where("e", Predicates.abilities(PartAbility.MUFFLER).setMaxGlobalLimited(1, 1))
                    .where('h', Predicates.controller(Predicates.blocks(definition.get())))
                    .build()
            )
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Abilities: Perfect Overclock, Parallel Hatch and Threading").withStyle(style -> style.withColor(0xFFD700)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Created for ultra-fast distillation.").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Available Recipe Types: Distillation Tower, Distillery").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("Allows non-positional distillating.").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("Accepts Threading Core T3.").withStyle(ChatFormatting.LIGHT_PURPLE))
            .workableCasingModel(
                    GTCEu.id("block/casings/gcym/watertight_casing"),
                    GTCEu.id("block/multiblock/distillation_tower")
            )
            .register();

    public static final MachineDefinition GIANT_WIRE_FACTORY = REGISTRATE
            .multiblock("giant_wire_factory", ThreadedMultiblockBase::new)
            .rotationState(RotationState.ALL)
            .recipeTypes(GTRecipeTypes.WIREMILL_RECIPES)
            .recipeModifiers(GTRecipeModifiers.OC_PERFECT, GTRecipeModifiers.PARALLEL_HATCH)
            .appearanceBlock(GCYMBlocks.CASING_STRESS_PROOF)
            .pattern(definition -> FactoryBlockPattern.start()
                    .aisle("bbaaaaabb", "bbbbcbbbb", "bbbbcbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb")
                    .aisle("badddddab", "bbbbbbbbb", "bbbbbbbbb", "bbbbcbbbb", "bbbbcbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb")
                    .aisle("adadddada", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbcbbbb", "bbbbcbbbb", "bbbbcbbbb", "bbbbcbbbb", "bbbbcbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb")
                    .aisle("addaaadda", "bbbaaabbb", "bbbeeebbb", "bbbeeebbb", "bbbeeebbb", "bbbaaabbb", "bbbeeebbb", "bbbeeebbb", "bbbeeebbb", "bbbaaabbb", "bbbbcbbbb", "bbbbcbbbb", "bbbbbbbbb", "bbbbbbbbb")
                    .aisle("addaaadda", "cbbafabbc", "cbbefebbc", "bcbefebcb", "bcbefebcb", "bbcafacbb", "bbcefecbb", "bbcefecbb", "bbcefecbb", "bbcafacbb", "bbbcdcbbb", "bbbcdcbbb", "bbbbcbbbb", "bbbbcbbbb")
                    .aisle("addaaadda", "bbbaaabbb", "bbbeeebbb", "bbbeeebbb", "bbbeeebbb", "bbbaaabbb", "bbbeeebbb", "bbbeeebbb", "bbbeeebbb", "bbbaaabbb", "bbbbcbbbb", "bbbbcbbbb", "bbbbbbbbb", "bbbbbbbbb")
                    .aisle("adadddada", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbcbbbb", "bbbbcbbbb", "bbbbcbbbb", "bbbbcbbbb", "bbbbcbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb")
                    .aisle("badddddab", "bbbbbbbbb", "bbbbbbbbb", "bbbbcbbbb", "bbbbcbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb")
                    .aisle("bbaahaabb", "bbbbcbbbb", "bbbbcbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb", "bbbbbbbbb")
                    .where("a", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:stress_proof_casing")))
                            .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2).setPreviewCount(2))
                            .or(Predicates.abilities(PartAbility.MAINTENANCE).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(ThreadT3PartMachine.getPartAbility()).setMaxGlobalLimited(1).setPreviewCount(1)))
                    .where("b", Predicates.any())
                    .where("c", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:naquadah_alloy_frame"))))
                    .where("d", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:solid_machine_casing"))))
                    .where("e", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:tempered_glass"))))
                    .where("f", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:steel_gearbox"))))
                    .where('h', Predicates.controller(Predicates.blocks(definition.get())))
                    .build()
            )
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Abilities: Perfect Overclock, Parallel Hatch and Threading").withStyle(style -> style.withColor(0xFFD700)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Created for ultra-fast wiremilling.").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Available Recipe Type: Wiremill").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("Accepts Threading Core T3.").withStyle(ChatFormatting.LIGHT_PURPLE))
            .workableCasingModel(
                    GTCEu.id("block/casings/gcym/stress_proof_casing"),
                    GTCEu.id("block/multiblock/distillation_tower")
            )
            .register();

    public static final MachineDefinition GIANT_MATERIAL_PRESS = REGISTRATE
            .multiblock("giant_material_press", ThreadedMultiblockBase::new)
            .rotationState(RotationState.ALL)
            .recipeTypes(GTRecipeTypes.BENDER_RECIPES, GTRecipeTypes.COMPRESSOR_RECIPES, GTRecipeTypes.FORGE_HAMMER_RECIPES, GTRecipeTypes.FORMING_PRESS_RECIPES)
            .recipeModifiers(GTRecipeModifiers.OC_PERFECT, GTRecipeModifiers.PARALLEL_HATCH)
            .appearanceBlock(GCYMBlocks.CASING_STRESS_PROOF)
            .pattern(definition -> FactoryBlockPattern.start()
                    .aisle("aaaaaaa", "bcccccb", "bcccccb", "bcccccb", "aaaaaaa", "bcccccb", "bcccccb", "bcccccb", "aaaaaaa")
                    .aisle("addddda", "caeeeac", "caeeeac", "caeeeac", "aadddaa", "caeeeac", "caeeeac", "caeeeac", "addddda")
                    .aisle("addddda", "cefgfec", "cefgfec", "cefgfec", "adfffda", "cefgfec", "cefgfec", "cefgfec", "addddda")
                    .aisle("addddda", "cegfgec", "cegcgec", "cegcgec", "adfcfda", "cegcgec", "cegcgec", "cegfgec", "addddda")
                    .aisle("addddda", "cefgfec", "cefgfec", "cefgfec", "adfffda", "cefgfec", "cefgfec", "cefgfec", "addddda")
                    .aisle("addddda", "caeeeac", "caeeeac", "caeeeac", "aadddaa", "caeeeac", "caeeeac", "caeeeac", "addddda")
                    .aisle("aaahaaa", "bcccccb", "bcccccb", "bcccccb", "aaaaaaa", "bcccccb", "bcccccb", "bcccccb", "aaaaaaa")
                    .where("a", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:stress_proof_casing")))
                            .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2).setPreviewCount(2))
                            .or(Predicates.abilities(PartAbility.MAINTENANCE).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(ThreadT3PartMachine.getPartAbility()).setMaxGlobalLimited(1).setPreviewCount(1)))
                    .where("b", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:steel_frame"))))
                    .where("c", Predicates.any())
                    .where("d", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:solid_machine_casing"))))
                    .where("e", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:tempered_glass"))))
                    .where("f", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:sturdy_machine_casing"))))
                    .where("g", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:titanium_gearbox"))))
                    .where('h', Predicates.controller(Predicates.blocks(definition.get())))
                    .build()
            )
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Abilities: Perfect Overclock, Parallel Hatch and Threading").withStyle(style -> style.withColor(0xFFD700)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Created for ultra-fast material pressing.").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Available Recipe Types: Bender, Compressor, Forge Hammer and Forming Press").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("Accepts Threading Core T3.").withStyle(ChatFormatting.LIGHT_PURPLE))
            .workableCasingModel(
                    GTCEu.id("block/casings/gcym/stress_proof_casing"),
                    GTCEu.id("block/multiblock/distillation_tower")
            )
            .register();

    public static final MachineDefinition GIANT_EXTRUSION_MACHINE = REGISTRATE
            .multiblock("giant_extrusion_machine", ThreadedMultiblockBase::new)
            .rotationState(RotationState.ALL)
            .recipeType(GTRecipeTypes.EXTRUDER_RECIPES)
            .recipeModifiers(GTRecipeModifiers.OC_PERFECT, GTRecipeModifiers.PARALLEL_HATCH)
            .appearanceBlock(GCYMBlocks.CASING_STRESS_PROOF)
            .pattern(definition -> FactoryBlockPattern.start()
                    .aisle("aaaaaaaaa", "addddddda", "addddddda", "addddddda", "aaaaaaaaa")
                    .aisle("abbbbbbba", "beeeeeeeb", "begeeegeb", "beeeeeeeb", "abbbbbbba")
                    .aisle("abbbbbbba", "bfgfffgfb", "ccccccccc", "bfgfffgfb", "abbbbbbba")
                    .aisle("abbbbbbba", "beeeeeeeb", "begeeegeb", "beeeeeeeb", "abbbbbbba")
                    .aisle("aaaahaaaa", "addddddda", "addddddda", "addddddda", "aaaaaaaaa")
                    .where("a", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:stress_proof_casing")))
                            .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2).setPreviewCount(2))
                            .or(Predicates.abilities(PartAbility.MAINTENANCE).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(ThreadT3PartMachine.getPartAbility()).setMaxGlobalLimited(1).setPreviewCount(1)))
                    .where("b", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:solid_machine_casing"))))
                    .where("c", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:titanium_pipe_casing"))))
                    .where("d", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:tempered_glass"))))
                    .where("e", Predicates.any())
                    .where("f", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:clean_machine_casing"))))
                    .where("g", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:steel_gearbox"))))
                    .where('h', Predicates.controller(Predicates.blocks(definition.get())))
                    .build()
            )
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Abilities: Perfect Overclock, Parallel Hatch and Threading").withStyle(style -> style.withColor(0xFFD700)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Created for ultra-fast extruding.").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Available Recipe Type: Extruder").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("Accepts Threading Core T3.").withStyle(ChatFormatting.LIGHT_PURPLE))
            .workableCasingModel(
                    GTCEu.id("block/casings/gcym/stress_proof_casing"),
                    GTCEu.id("block/multiblock/distillation_tower")
            )
            .register();

    public static final MachineDefinition GIANT_ASSEMBLER_CIRCUIT = REGISTRATE
            .multiblock("giant_assembler_circuit", ThreadedMultiblockBase::new)
            .rotationState(RotationState.ALL)
            .recipeType(GTRecipeTypes.CIRCUIT_ASSEMBLER_RECIPES)
            .recipeModifiers(GTRecipeModifiers.OC_PERFECT, GTRecipeModifiers.PARALLEL_HATCH)
            .appearanceBlock(GCYMBlocks.CASING_LARGE_SCALE_ASSEMBLING)
            .pattern(definition -> FactoryBlockPattern.start()
                    .aisle("bbbbaaaaabbbb", "bbbbcbbbcbbbb", "bbbbcbbbcbbbb", "bbbbbcbcbbbbb", "bbbbbcbcbbbbb", "bbbbbbcbbbbbb", "bbbbbcbcbbbbb", "bbbbbcbcbbbbb", "bbbbcbbbcbbbb", "bbbbcbbbcbbbb", "bbbbaaaaabbbb")
                    .aisle("bbaadddddaabb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbaadddddaabb")
                    .aisle("baddadddaddab", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "baddadddaddab")
                    .aisle("badddadadddab", "bbbaaadaaabbb", "bbbeeebeeebbb", "bbbeeebeeebbb", "bbbeeebeeebbb", "bbbafabafabbb", "bbbeeebeeebbb", "bbbeeebeeebbb", "bbbeeebeeebbb", "bbbaaadaaabbb", "badddadadddab")
                    .aisle("adadddadddada", "cbbaaadaaabbc", "cbbegebegebbc", "bbbegebegebbb", "bbbegebegebbb", "bbbfgfbfgfbbb", "bbbegebegebbb", "bbbegebegebbb", "cbbegebegebbc", "cbbaaadaaabbc", "adadddadddada")
                    .aisle("addaddaddadda", "bbbaaadaaabbb", "bbbeeebeeebbb", "cbbebebeeebbc", "cbbeeebeeebbc", "bbbafabafabbb", "cbbeeebeeebbc", "cbbeeebeeebbc", "bbbeeebeeebbb", "bbbaaadaaabbb", "addaddaddadda")
                    .aisle("adddaaaaaddda", "bbbdddddddbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "cbbbbbbbbbbbc", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbdddddddbbb", "adddaaaaaddda")
                    .aisle("addaddaddadda", "bbbaaadaaabbb", "bbbeeebeeebbb", "cbbeeebeeebbc", "cbbeeebeeebbc", "bbbafabafabbb", "cbbeeebeeebbc", "cbbeeebeeebbc", "bbbeeebeeebbb", "bbbaaadaaabbb", "addaddaddadda")
                    .aisle("adadddadddada", "cbbaaadaaabbc", "cbbegebegebbc", "bbbegebegebbb", "bbbegebegebbb", "bbbfgfbfgfbbb", "bbbegebegebbb", "bbbegebegebbb", "cbbegebegebbc", "cbbaaadaaabbc", "adadddadddada")
                    .aisle("badddadadddab", "bbbaaadaaabbb", "bbbeeebeeebbb", "bbbeeebeeebbb", "bbbeeebeeebbb", "bbbafabafabbb", "bbbeeebeeebbb", "bbbeeebeeebbb", "bbbeeebeeebbb", "bbbaaadaaabbb", "badddadadddab")
                    .aisle("baddadddaddab", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "baddadddaddab")
                    .aisle("bbaadddddaabb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbaadddddaabb")
                    .aisle("bbbbaahaabbbb", "bbbbcbbbcbbbb", "bbbbcbbbcbbbb", "bbbbbcbcbbbbb", "bbbbbcbcbbbbb", "bbbbbbcbbbbbb", "bbbbbcbcbbbbb", "bbbbbcbcbbbbb", "bbbbcbbbcbbbb", "bbbbcbbbcbbbb", "bbbbaaaaabbbb")
                    .where("a", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:large_scale_assembler_casing")))
                            .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2).setPreviewCount(2))
                            .or(Predicates.abilities(PartAbility.MAINTENANCE).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(ThreadT3PartMachine.getPartAbility()).setMaxGlobalLimited(1).setPreviewCount(1)))
                    .where("b", Predicates.any())
                    .where("c", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:black_steel_frame"))))
                    .where("d", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:high_temperature_smelting_casing"))))
                    .where("e", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:fusion_glass"))))
                    .where("f", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gregecore:assembly_engine_intake"))))
                    .where("g", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:assembly_line_unit"))))
                    .where('h', Predicates.controller(Predicates.blocks(definition.get())))
                    .build()
            )
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Abilities: Perfect Overclock, Parallel Hatch and Threading").withStyle(style -> style.withColor(0xFFD700)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Created for ultra-fast circuit assembling.").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Available Recipe Type: Circuit Assembler").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("Accepts Threading Core T3.").withStyle(ChatFormatting.LIGHT_PURPLE))
            .workableCasingModel(
                    GTCEu.id("block/casings/gcym/large_scale_assembling_casing"),
                    GTCEu.id("block/multiblock/distillation_tower")
            )
            .register();

    public static final MachineDefinition GIANT_ASSEMBLER = REGISTRATE
            .multiblock("giant_assembler", ThreadedMultiblockBase::new)
            .rotationState(RotationState.ALL)
            .recipeType(GTRecipeTypes.ASSEMBLER_RECIPES)
            .recipeModifiers(GTRecipeModifiers.OC_PERFECT, GTRecipeModifiers.PARALLEL_HATCH)
            .appearanceBlock(GCYMBlocks.CASING_LARGE_SCALE_ASSEMBLING)
            .pattern(definition -> FactoryBlockPattern.start()
                    .aisle("baaabbbbbaaab", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "baaabbbbbaaab")
                    .aisle("aaaaabbbaaaaa", "baaabbbbbaaab", "bcccbbbbbcccb", "bcccbbbbbcccb", "bcccbbbbbcccb", "badabbbbbadab", "bcccbbbbbcccb", "bcccbbbbbcccb", "bcccbbbbbcccb", "badabbbbbadab", "bcccbbbbbcccb", "bcccbbbbbcccb", "bcccbbbbbcccb", "baaabbbbbaaab", "aaaaabbbaaaaa")
                    .aisle("aaaaabbbaaaaa", "baeabbbbbaeab", "bcecbbbbbcecb", "bcfcbbbbbcfcb", "bcecbbbbbcecb", "bdedbbbbbdedb", "bcecbbbbbcecb", "bcfcbbbbbcfcb", "bcecbbbbbcecb", "bdedbbbbbdedb", "bcecbbbbbcecb", "bcfcbbbbbcfcb", "bcecbbbbbcecb", "baeabbbbbaeab", "aaaaabbbaaaaa")
                    .aisle("aaaaabbbaaaaa", "baaabbbbbaaab", "bcccbbbbbcccb", "bcccbbbbbcccb", "bcccbbbbbcccb", "bgdgbbbbbadab", "bcccbbbbbcccb", "bcecbbbbbcecb", "bcccbbbbbcccb", "badabbbbbadab", "bcccbbbbbcccb", "bcccbbbbbcccb", "bcccbbbbbcccb", "baaabbbbbaaab", "aaaaabbbaaaaa")
                    .aisle("baaabbbbbaaab", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bcccbbbbbcccb", "bcecbbbbbcecb", "bcccbbbbbcccb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "baaabbbbbaaab")
                    .aisle("bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bccccgggccccb", "bcfcgghggcfcb", "bccccgggccccb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb")
                    .aisle("bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bcccgghggcccb", "bcfffeeefffcb", "bcccgghggcccb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb")
                    .aisle("bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bccccgggccccb", "bcfcggiggcfcb", "bccccgggccccb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb")
                    .aisle("baaabbbbbaaab", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bcccbbbbbcccb", "bcecbbbbbcecb", "bcccbbbbbcccb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "baaabbbbbaaab")
                    .aisle("aaaaabbbaaaaa", "baaabbbbbaaab", "bcccbbbbbcccb", "bcccbbbbbcccb", "bcccbbbbbcccb", "badabbbbbadab", "bcccbbbbbcccb", "bcecbbbbbcecb", "bcccbbbbbcccb", "badabbbbbadab", "bcccbbbbbcccb", "bcccbbbbbcccb", "bcccbbbbbcccb", "baaabbbbbaaab", "aaaaabbbaaaaa")
                    .aisle("aaaaabbbaaaaa", "baeabbbbbaeab", "bcecbbbbbcecb", "bcfcbbbbbcfcb", "bcecbbbbbcecb", "bdedbbbbbdedb", "bcecbbbbbcecb", "bcfcbbbbbcfcb", "bcecbbbbbcecb", "bdedbbbbbdedb", "bcecbbbbbcecb", "bcfcbbbbbcfcb", "bcecbbbbbcecb", "baeabbbbbaaab", "aaaaabbbaaaaa")
                    .aisle("aaaaabbbaaaaa", "baaabbbbbaaab", "bcccbbbbbcccb", "bcccbbbbbcccb", "bcccbbbbbcccb", "badabbbbbadab", "bcccbbbbbcccb", "bcccbbbbbcccb", "bcccbbbbbcccb", "badabbbbbadab", "bcccbbbbbcccb", "bcccbbbbbcccb", "bcccbbbbbcccb", "baaabbbbbaaab", "aaaaabbbaaaaa")
                    .aisle("baaabbbbbaaab", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "bbbbbbbbbbbbb", "baaabbbbbaaab")
                    .where("a", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:large_scale_assembler_casing")))
                            .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2).setPreviewCount(2))
                            .or(Predicates.abilities(PartAbility.MAINTENANCE).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(ThreadT3PartMachine.getPartAbility()).setMaxGlobalLimited(1).setPreviewCount(1)))
                    .where("b", Predicates.any())
                    .where("c", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:laminated_glass"))))
                    .where("d", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gregecore:assembly_engine_intake"))))
                    .where("e", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:assembly_line_unit"))))
                    .where("f", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:steel_gearbox"))))
                    .where("g", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:solid_machine_casing"))))
                    .where("h", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gregecore:solid_engine_intake"))))
                    .where('i', Predicates.controller(Predicates.blocks(definition.get())))
                    .build()
            )
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Abilities: Perfect Overclock, Parallel Hatch and Threading").withStyle(style -> style.withColor(0xFFD700)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Created for ultra-fast assembling.").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Available Recipe Type: Assembler").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("Accepts Threading Core T3.").withStyle(ChatFormatting.LIGHT_PURPLE))
            .workableCasingModel(
                    GTCEu.id("block/casings/gcym/large_scale_assembling_casing"),
                    GTCEu.id("block/multiblock/distillation_tower")
            )
            .register();

    public static final MachineDefinition GIANT_SIFTER = REGISTRATE
            .multiblock("giant_sifter", ThreadedMultiblockBase::new)
            .rotationState(RotationState.ALL)
            .recipeType(GTRecipeTypes.SIFTER_RECIPES)
            .recipeModifiers(GTRecipeModifiers.OC_PERFECT, GTRecipeModifiers.PARALLEL_HATCH)
            .appearanceBlock(GCYMBlocks.CASING_VIBRATION_SAFE)
            .pattern(definition -> FactoryBlockPattern.start()
                    .aisle("abababa", "abababa", "abababa", "bbbbbbb", "abababa")
                    .aisle("bbbbbbb", "bbbbbbb", "bbbbbbb", "bbbbbbb", "bbbbbbb")
                    .aisle("abbbbba", "abaaaba", "abaaaba", "bbcccbb", "abaaaba")
                    .aisle("bbbbbbb", "bbaaabb", "bbaaabb", "bbcccbb", "bbaaabb")
                    .aisle("abbbbba", "abaaaba", "abaaaba", "bbcccbb", "abaaaba")
                    .aisle("bbbbbbb", "bbbbbbb", "bbbbbbb", "bbbbbbb", "bbbbbbb")
                    .aisle("abaiaba", "abababa", "abababa", "bbbbbbb", "abababa")
                    .where("a", Predicates.any())
                    .where("b", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:vibration_safe_casing")))
                            .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2).setPreviewCount(2))
                            .or(Predicates.abilities(PartAbility.MAINTENANCE).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(ThreadT3PartMachine.getPartAbility()).setMaxGlobalLimited(1).setPreviewCount(1)))
                    .where("c", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:assembly_line_grating"))))
                    .where('i', Predicates.controller(Predicates.blocks(definition.get())))
                    .build()
            )
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Abilities: Perfect Overclock, Parallel Hatch and Threading").withStyle(style -> style.withColor(0xFFD700)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Created for ultra-fast sifting.").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Available Recipe Type: Sifter").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("Accepts Threading Core T3.").withStyle(ChatFormatting.LIGHT_PURPLE))
            .workableCasingModel(
                    GTCEu.id("block/casings/gcym/vibration_safe_casing"),
                    GTCEu.id("block/multiblock/distillation_tower")
            )
            .register();

    public static final MachineDefinition GIANT_CENTRIFUGE = REGISTRATE
            .multiblock("giant_centrifuge", ThreadedMultiblockBase::new)
            .rotationState(RotationState.ALL)
            .recipeTypes(GTRecipeTypes.CENTRIFUGE_RECIPES, GTRecipeTypes.THERMAL_CENTRIFUGE_RECIPES)
            .recipeModifiers(GTRecipeModifiers.OC_PERFECT, GTRecipeModifiers.PARALLEL_HATCH)
            .appearanceBlock(GCYMBlocks.CASING_VIBRATION_SAFE)
            .pattern(definition -> FactoryBlockPattern.start()
                    .aisle("bbbbbbbbb", "bbbaaabbb", "bbbcccbbb", "bbbaaabbb", "bbbbbbbbb")
                    .aisle("bbbaaabbb", "bbabbbabb", "bbcbbbcbb", "bbabbbabb", "bbbaaabbb")
                    .aisle("bbaaaaabb", "babbbbbab", "bcbbdbbcb", "babbbbbab", "bbaaaaabb")
                    .aisle("baaaaaaab", "abbbbbbba", "cbbbdbbbc", "abbbbbbba", "baaaaaaab")
                    .aisle("baaaeaaab", "abbbebbba", "cbddeddbc", "abbbebbba", "baaaeaaab")
                    .aisle("baaaaaaab", "abbbbbbba", "cbbbdbbbc", "abbbbbbba", "baaaaaaab")
                    .aisle("bbaaaaabb", "babbbbbab", "bcbbdbbcb", "babbbbbab", "bbaaaaabb")
                    .aisle("bbbaaabbb", "bbabbbabb", "bbcbbbcbb", "bbabbbabb", "bbbaaabbb")
                    .aisle("bbbbibbbb", "bbbaaabbb", "bbbcccbbb", "bbbaaabbb", "bbbbbbbbb")
                    .where("a", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:vibration_safe_casing")))
                            .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2).setPreviewCount(2))
                            .or(Predicates.abilities(PartAbility.MAINTENANCE).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(ThreadT3PartMachine.getPartAbility()).setMaxGlobalLimited(1).setPreviewCount(1)))
                    .where("b", Predicates.any())
                    .where("c", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:laminated_glass"))))
                    .where("d", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:steel_pipe_casing"))))
                    .where("e", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:nonconducting_casing"))))
                    .where('i', Predicates.controller(Predicates.blocks(definition.get())))
                    .build()
            )
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Abilities: Perfect Overclock, Parallel Hatch and Threading").withStyle(style -> style.withColor(0xFFD700)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Created for ultra-fast centrifuging.").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Available Recipe Types: Centrifuge and Thermal Centrifuge").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("Accepts Threading Core T3.").withStyle(ChatFormatting.LIGHT_PURPLE))
            .workableCasingModel(
                    GTCEu.id("block/casings/gcym/vibration_safe_casing"),
                    GTCEu.id("block/multiblock/distillation_tower")
            )
            .register();

    public static final MachineDefinition GIANT_ELECTROMAGNET = REGISTRATE
            .multiblock("giant_electromagnet", ThreadedMultiblockBase::new)
            .rotationState(RotationState.ALL)
            .recipeTypes(GTRecipeTypes.ELECTROMAGNETIC_SEPARATOR_RECIPES, GTRecipeTypes.POLARIZER_RECIPES)
            .recipeModifiers(GTRecipeModifiers.OC_PERFECT, GTRecipeModifiers.PARALLEL_HATCH)
            .appearanceBlock(GCYMBlocks.CASING_HIGH_TEMPERATURE_SMELTING)
            .pattern(definition -> FactoryBlockPattern.start()
                    .aisle("abbbbba", "accccca", "accccca", "accccca", "accccca", "accccca", "abbbbba")
                    .aisle("bdddddb", "ceeeeec", "ceeeeec", "ceeeeec", "ceeeeec", "ceeeeec", "bdddddb")
                    .aisle("bdddddb", "cefffec", "cefffec", "cefffec", "cefffec", "cefffec", "bdddddb")
                    .aisle("bdddddb", "cefgfec", "cefgfec", "cefgfec", "cefgfec", "cefgfec", "bdddddb")
                    .aisle("bdddddb", "cefffec", "cefffec", "cefffec", "cefffec", "cefffec", "bdddddb")
                    .aisle("bdddddb", "ceeeeec", "ceeeeec", "ceeeeec", "ceeeeec", "ceeeeec", "bdddddb")
                    .aisle("abbibba", "accccca", "accccca", "accccca", "accccca", "accccca", "abbbbba")
                    .where("a", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:steel_frame"))))
                    .where("b", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:high_temperature_smelting_casing")))
                            .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2).setPreviewCount(2))
                            .or(Predicates.abilities(PartAbility.MAINTENANCE).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(ThreadT3PartMachine.getPartAbility()).setMaxGlobalLimited(1).setPreviewCount(1)))
                    .where("c", Predicates.any())
                    .where("d", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:nonconducting_casing"))))
                    .where("e", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:laminated_glass"))))
                    .where("f", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:electrolytic_cell"))))
                    .where("g", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:cupronickel_coil_block"))))
                    .where('i', Predicates.controller(Predicates.blocks(definition.get())))
                    .build()
            )
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Abilities: Perfect Overclock, Parallel Hatch and Threading").withStyle(style -> style.withColor(0xFFD700)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Created for ultra-fast magnetizing.").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Available Recipe Types: Electromagnetic Separator and Polarizer").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("Accepts Threading Core T3.").withStyle(ChatFormatting.LIGHT_PURPLE))
            .workableCasingModel(
                    GTCEu.id("block/casings/gcym/high_temperature_smelting_casing"),
                    GTCEu.id("block/multiblock/distillation_tower")
            )
            .register();

    public static final MachineDefinition GIANT_ELECTROLYZER = REGISTRATE
            .multiblock("giant_electrolyzer", ThreadedMultiblockBase::new)
            .rotationState(RotationState.ALL)
            .recipeTypes(GTRecipeTypes.ELECTROLYZER_RECIPES)
            .recipeModifiers(GTRecipeModifiers.OC_PERFECT, GTRecipeModifiers.PARALLEL_HATCH)
            .appearanceBlock(GCYMBlocks.CASING_HIGH_TEMPERATURE_SMELTING)
            .pattern(definition -> FactoryBlockPattern.start()
                    .aisle("aaaaaaa", "abbbbba", "abbbbba", "aaaaaaa")
                    .aisle("abbbbba", "bcccccb", "bcccccb", "addddda")
                    .aisle("abbbbba", "bceeecb", "bceeecb", "addddda")
                    .aisle("abbbbba", "bcececb", "bcececb", "addddda")
                    .aisle("abbbbba", "bceeecb", "bceeecb", "addddda")
                    .aisle("abbbbba", "bcccccb", "bcccccb", "addddda")
                    .aisle("aaaiaaa", "abbbbba", "abbbbba", "aaaaaaa")
                    .where("a", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:high_temperature_smelting_casing")))
                            .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2).setPreviewCount(2))
                            .or(Predicates.abilities(PartAbility.MAINTENANCE).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(ThreadT3PartMachine.getPartAbility()).setMaxGlobalLimited(1).setPreviewCount(1)))
                    .where("b", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:nonconducting_casing"))))
                    .where("c", Predicates.any())
                    .where("d", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:tempered_glass"))))
                    .where("e", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:electrolytic_cell"))))
                    .where('i', Predicates.controller(Predicates.blocks(definition.get())))
                    .build()
            )
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Abilities: Perfect Overclock, Parallel Hatch and Threading").withStyle(style -> style.withColor(0xFFD700)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Created for ultra-fast electrolyzing.").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Available Recipe Type: Electrolyzer").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("Accepts Threading Core T3.").withStyle(ChatFormatting.LIGHT_PURPLE))
            .workableCasingModel(
                    GTCEu.id("block/casings/gcym/high_temperature_smelting_casing"),
                    GTCEu.id("block/multiblock/distillation_tower")
            )
            .register();

    public static final MachineDefinition GIANT_MACERATOR = REGISTRATE
            .multiblock("giant_macerator", ThreadedMultiblockBase::new)
            .rotationState(RotationState.ALL)
            .recipeTypes(GTRecipeTypes.MACERATOR_RECIPES)
            .recipeModifiers(GTRecipeModifiers.OC_PERFECT, GTRecipeModifiers.PARALLEL_HATCH)
            .appearanceBlock(GCYMBlocks.CASING_SECURE_MACERATION)
            .pattern(definition -> FactoryBlockPattern.start()
                    .aisle("aaaaaaaa", "abbbbbba", "abbbbbba", "aaaaaaaa")
                    .aisle("abbbbbba", "bdcccccb", "bdddeeeb", "abbaddda")
                    .aisle("abbbbbba", "bdcdcccb", "bdddeeeb", "abbaddda")
                    .aisle("abbbbbba", "bdcdcccb", "bdddeeeb", "abbaddda")
                    .aisle("aaaaaaia", "afcfabba", "afffabba", "aaaaaaaa")
                    .where("a", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:secure_maceration_casing")))
                            .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2).setPreviewCount(2))
                            .or(Predicates.abilities(PartAbility.MAINTENANCE).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(ThreadT3PartMachine.getPartAbility()).setMaxGlobalLimited(1).setPreviewCount(1)))
                    .where("b", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:stress_proof_casing"))))
                    .where("c", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:tungstensteel_pipe_casing"))))
                    .where("d", Predicates.any())
                    .where("e", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:crushing_wheels"))))
                    .where("f", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:tempered_glass"))))
                    .where('i', Predicates.controller(Predicates.blocks(definition.get())))
                    .build()
            )
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Abilities: Perfect Overclock, Parallel Hatch and Threading").withStyle(style -> style.withColor(0xFFD700)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Created for ultra-fast macerating.").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Available Recipe Type: Macerator").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("Accepts Threading Core T3.").withStyle(ChatFormatting.LIGHT_PURPLE))
            .workableCasingModel(
                    GTCEu.id("block/casings/gcym/secure_maceration_casing"),
                    GTCEu.id("block/multiblock/distillation_tower")
            )
            .register();

    public static final MachineDefinition GIANT_MIXER = REGISTRATE
            .multiblock("giant_mixer", ThreadedMultiblockBase::new)
            .rotationState(RotationState.ALL)
            .recipeTypes(GTRecipeTypes.MIXER_RECIPES)
            .recipeModifiers(GTRecipeModifiers.OC_PERFECT, GTRecipeModifiers.PARALLEL_HATCH)
            .appearanceBlock(GCYMBlocks.CASING_SECURE_MACERATION)
            .pattern(definition -> FactoryBlockPattern.start()
                    .aisle("aaaaaaa", "aaaaaaa", "aaaaaaa", "aaaaaaa", "aacbcaa", "aacbcaa", "aacbcaa", "aabbbaa", "aaadaaa", "aaaaaaa")
                    .aisle("aaaaaaa", "aacbcaa", "aacbcaa", "aacbcaa", "acaaaca", "acaeaca", "acaaaca", "abaaaba", "aaadaaa", "aaaaaaa")
                    .aisle("aacbcaa", "acaaaca", "acaeaca", "acaaaca", "caaaaac", "caaeaac", "caaaaac", "baaaaab", "aaadaaa", "aaaaaaa")
                    .aisle("aabbcaa", "abaeaba", "abeeeba", "abaeaba", "baaeaab", "beeeeeb", "baaeaab", "baaeaab", "dddfddd", "aaadaaa")
                    .aisle("aacbcaa", "acaaaca", "acaeaca", "acaaaca", "caaaaac", "caaeaac", "caaaaac", "baaaaab", "aaadaaa", "aaaaaaa")
                    .aisle("aaaaaaa", "aacicaa", "aacbcaa", "aacbcaa", "acaaaca", "acaeaca", "acaaaca", "abaaaba", "aaadaaa", "aaaaaaa")
                    .aisle("aaaaaaa", "aaaaaaa", "aaaaaaa", "aaaaaaa", "aacbcaa", "aacbcaa", "aacbcaa", "aabbbaa", "aaadaaa", "aaaaaaa")

                    .where("a", Predicates.any())
                    .where("b", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:secure_maceration_casing")))
                            .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2).setPreviewCount(2))
                            .or(Predicates.abilities(PartAbility.MAINTENANCE).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(ThreadT3PartMachine.getPartAbility()).setMaxGlobalLimited(1).setPreviewCount(1)))
                    .where("c", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:reaction_safe_mixing_casing"))))
                    .where("d", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:blue_steel_frame"))))
                    .where("e", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:tungstensteel_pipe_casing"))))
                    .where("f", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:tungstensteel_gearbox"))))
                    .where('i', Predicates.controller(Predicates.blocks(definition.get())))
                    .build()
            )
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Abilities: Perfect Overclock, Parallel Hatch and Threading").withStyle(style -> style.withColor(0xFFD700)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Created for ultra-fast mixing.").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Available Recipe Type: Mixer").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("Accepts Threading Core T3.").withStyle(ChatFormatting.LIGHT_PURPLE))
            .workableCasingModel(
                    GTCEu.id("block/casings/gcym/secure_maceration_casing"),
                    GTCEu.id("block/multiblock/distillation_tower")
            )
            .register();

    public static final MachineDefinition GIANT_ENGRAVER = REGISTRATE
            .multiblock("giant_engraver", ThreadedMultiblockBase::new)
            .rotationState(RotationState.ALL)
            .recipeTypes(GTRecipeTypes.LASER_ENGRAVER_RECIPES)
            .recipeModifiers(GTRecipeModifiers.OC_PERFECT, GTRecipeModifiers.PARALLEL_HATCH)
            .appearanceBlock(GCYMBlocks.CASING_LASER_SAFE_ENGRAVING)
            .pattern(definition -> FactoryBlockPattern.start()
                    .aisle("aaaaaaaaa", "abbbabbba", "abbbabbba", "abbbabbba", "abbbabbba", "abbbabbba", "abbbabbba", "abbbabbba", "abbbabbba", "aaaaaaaaa")
                    .aisle("aaaacaaaa", "bdddddddb", "bdddddddb", "bdddddddb", "bdddddddb", "bdddddddb", "bdddddddb", "bdddddddb", "bdddddddb", "aeeeaeeea")
                    .aisle("aaaacaaaa", "bdddddddb", "bdddddddb", "bdddddddb", "bdddddddb", "bdddddddb", "bdddddddb", "bdddddddb", "bdddddddb", "aeeeaeeea")
                    .aisle("aaaacaaaa", "bdddddddb", "bdddddddb", "bdddddddb", "bdddddddb", "bdddddddb", "bdddddddb", "bdddcdddb", "bdddcdddb", "aeeeaeeea")
                    .aisle("accccccca", "adddfddda", "addddddda", "addddddda", "adddgddda", "adddaddda", "adddaddda", "addcacdda", "addcacdda", "aaaaaaaaa")
                    .aisle("aaaacaaaa", "bdddddddb", "bdddddddb", "bdddddddb", "bdddddddb", "bdddddddb", "bdddddddb", "bdddcdddb", "bdddcdddb", "aeeeaeeea")
                    .aisle("aaaacaaaa", "bdddddddb", "bdddddddb", "bdddddddb", "bdddddddb", "bdddddddb", "bdddddddb", "bdddddddb", "bdddddddb", "aeeeaeeea")
                    .aisle("aaaacaaaa", "bdddddddb", "bdddddddb", "bdddddddb", "bdddddddb", "bdddddddb", "bdddddddb", "bdddddddb", "bdddddddb", "aeeeaeeea")
                    .aisle("aaaaiaaaa", "abbbabbba", "abbbabbba", "abbbabbba", "abbbabbba", "abbbabbba", "abbbabbba", "abbbabbba", "abbbabbba", "aaaaaaaaa")

                    .where("a", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:laser_safe_engraving_casing")))
                            .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2).setPreviewCount(2))
                            .or(Predicates.abilities(PartAbility.MAINTENANCE).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(ThreadT3PartMachine.getPartAbility()).setMaxGlobalLimited(1).setPreviewCount(1)))
                    .where("b", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:tempered_glass"))))
                    .where("c", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:shock_proof_cutting_casing"))))
                    .where("d", Predicates.any())
                    .where("e", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:assembly_line_grating"))))
                    .where("f", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("relics:researching_table"))))
                    .where("g", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("minecraft:red_stained_glass"))))
                    .where('i', Predicates.controller(Predicates.blocks(definition.get())))
                    .build()
            )
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Abilities: Perfect Overclock, Parallel Hatch and Threading").withStyle(style -> style.withColor(0xFFD700)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Created for ultra-fast laser engraving.").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Available Recipe Type: Laser Engraver").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("Accepts Threading Core T3.").withStyle(ChatFormatting.LIGHT_PURPLE))
            .workableCasingModel(
                    GTCEu.id("block/casings/gcym/laser_safe_engraving_casing"),
                    GTCEu.id("block/multiblock/distillation_tower")
            )
            .register();

    public static final MachineDefinition GIANT_SAW = REGISTRATE
            .multiblock("giant_saw", ThreadedMultiblockBase::new)
            .rotationState(RotationState.ALL)
            .recipeTypes(GTRecipeTypes.LATHE_RECIPES, GTRecipeTypes.CUTTER_RECIPES)
            .recipeModifiers(GTRecipeModifiers.OC_PERFECT, GTRecipeModifiers.PARALLEL_HATCH)
            .appearanceBlock(GCYMBlocks.CASING_SHOCK_PROOF)
            .pattern(definition -> FactoryBlockPattern.start()
                    .aisle("aaaaaaaa", "afffabba", "afffabba", "aaaaaaaa")
                    .aisle("abbbbbba", "fecccccb", "feeedddb", "abbaeeea")
                    .aisle("abbbbbba", "fececccb", "feeedddb", "abbaeeea")
                    .aisle("abbbbbba", "fececccb", "feeedddb", "abbaeeea")
                    .aisle("abbbbbba", "fececccb", "feeedddb", "abbaeeea")
                    .aisle("aaaaaaia", "afcfabba", "afffabba", "aaaaaaaa")
                    .where("a", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:shock_proof_cutting_casing")))
                            .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2).setPreviewCount(2))
                            .or(Predicates.abilities(PartAbility.MAINTENANCE).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(ThreadT3PartMachine.getPartAbility()).setMaxGlobalLimited(1).setPreviewCount(1)))
                    .where("b", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:laser_safe_engraving_casing"))))
                    .where("c", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:titanium_pipe_casing"))))
                    .where("d", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:slicing_blades"))))
                    .where("e", Predicates.any())
                    .where("f", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:tempered_glass"))))
                    .where('i', Predicates.controller(Predicates.blocks(definition.get())))
                    .build()
            )
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Abilities: Perfect Overclock, Parallel Hatch and Threading").withStyle(style -> style.withColor(0xFFD700)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Created for ultra-fast laser sawing.").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Available Recipe Types: Lathe and Cutter").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("Accepts Threading Core T3.").withStyle(ChatFormatting.LIGHT_PURPLE))
            .workableCasingModel(
                    GTCEu.id("block/casings/gcym/shock_proof_cutting_casing"),
                    GTCEu.id("block/multiblock/distillation_tower")
            )
            .register();

    public static final MachineDefinition GIANT_ARC_FURNACE = REGISTRATE
            .multiblock("giant_arc_furnace", ThreadedMultiblockBase::new)
            .rotationState(RotationState.ALL)
            .recipeTypes(GTRecipeTypes.ARC_FURNACE_RECIPES)
            .recipeModifiers(GTRecipeModifiers.OC_PERFECT, GTRecipeModifiers.PARALLEL_HATCH)
            .appearanceBlock(GCYMBlocks.CASING_STRESS_PROOF)
            .pattern(definition -> FactoryBlockPattern.start()
                    .aisle("abbbbba", "aaaaaaa", "aaaaaaa", "aaaaaaa", "aaaaaaa", "aaaaaaa", "aaaaaaa", "aaaaaaa", "abbbbba")
                    .aisle("bbcccbb", "adeeeda", "adfefda", "adfefda", "adeeeda", "adfefda", "adfefda", "adeeeda", "bbcccbb")
                    .aisle("bcccccb", "aeaaaea", "afaaafa", "afaaafa", "aeaaaea", "afaaafa", "afaaafa", "aeaaaea", "bcccccb")
                    .aisle("bcccccb", "aeaaaea", "aeaaaea", "aeaaaea", "aeaaaea", "aeaaaea", "aeaaaea", "aeaaaea", "bcccccb")
                    .aisle("bcccccb", "aeaaaea", "afaaafa", "afaaafa", "aeaaaea", "afaaafa", "afaaafa", "aeaaaea", "bcccccb")
                    .aisle("bbcccbb", "adeeeda", "adfefda", "adfefda", "adeeeda", "adfefda", "adfefda", "adeeeda", "bbcccbb")
                    .aisle("abbibba", "aaaaaaa", "aaaaaaa", "aaaaaaa", "aaaaaaa", "aaaaaaa", "aaaaaaa", "aaaaaaa", "abbbbba")

                    .where("a", Predicates.any())
                    .where("b", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:stress_proof_casing")))
                            .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2).setPreviewCount(2))
                            .or(Predicates.abilities(PartAbility.MAINTENANCE).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(ThreadT3PartMachine.getPartAbility()).setMaxGlobalLimited(1).setPreviewCount(1)))
                    .where("c", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:solid_machine_casing"))))
                    .where("d", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:black_steel_frame"))))
                    .where("e", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:high_temperature_smelting_casing"))))
                    .where("f", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:cupronickel_coil_block"))))
                    .where('i', Predicates.controller(Predicates.blocks(definition.get())))
                    .build()
            )
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Abilities: Perfect Overclock, Parallel Hatch and Threading").withStyle(style -> style.withColor(0xFFD700)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Created for ultra-fast arc smelting.").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Available Recipe Type: Arc Smelter").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("Accepts Threading Core T3.").withStyle(ChatFormatting.LIGHT_PURPLE))
            .workableCasingModel(
                    GTCEu.id("block/casings/gcym/stress_proof_casing"),
                    GTCEu.id("block/multiblock/distillation_tower")
            )
            .register();

    public static final MachineDefinition GIANT_BREWERY = REGISTRATE
            .multiblock("giant_brewery", ThreadedMultiblockBase::new)
            .rotationState(RotationState.ALL)
            .recipeTypes(GTRecipeTypes.BREWING_RECIPES, GTRecipeTypes.FERMENTING_RECIPES, GTRecipeTypes.FLUID_HEATER_RECIPES)
            .recipeModifiers(GTRecipeModifiers.OC_PERFECT, GTRecipeModifiers.PARALLEL_HATCH)
            .appearanceBlock(GCYMBlocks.CASING_CORROSION_PROOF)
            .pattern(definition -> FactoryBlockPattern.start()
                    .aisle("bbaaabb", "bbacabb", "bbacabb", "bbaaabb", "bbaaabb", "bbacabb", "bbacabb", "bbaaabb", "bbbbbbb", "bbbbbbb")
                    .aisle("badddab", "babbbab", "babbbab", "baaaaab", "babbbab", "babbbab", "babbbab", "babbbab", "bbaaabb", "bbbbbbb")
                    .aisle("addddda", "abbbbba", "abbbbba", "aaaeaaa", "abbbbba", "abbbbba", "abbbbba", "abbbbba", "babbbab", "bbaaabb")
                    .aisle("addddda", "cbbbbbc", "cbbbbbc", "aaeeeaa", "abbbbba", "cbbbbbc", "cbbbbbc", "abbbbba", "babbbab", "bbaaabb")
                    .aisle("addddda", "abbbbba", "abbbbba", "aaaeaaa", "abbbbba", "abbbbba", "abbbbba", "abbbbba", "babbbab", "bbaaabb")
                    .aisle("badddab", "babbbab", "babbbab", "baaaaab", "babbbab", "babbbab", "babbbab", "babbbab", "bbaaabb", "bbbbbbb")
                    .aisle("bbaiabb", "bbacabb", "bbacabb", "bbaaabb", "bbaaabb", "bbacabb", "bbacabb", "bbaaabb", "bbbbbbb", "bbbbbbb")

                    .where("a", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:corrosion_proof_casing")))
                            .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(16).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMaxGlobalLimited(2).setPreviewCount(2))
                            .or(Predicates.abilities(PartAbility.MAINTENANCE).setMaxGlobalLimited(1).setPreviewCount(1))
                            .or(Predicates.abilities(ThreadT3PartMachine.getPartAbility()).setMaxGlobalLimited(1).setPreviewCount(1)))
                    .where("b", Predicates.any())
                    .where("c", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:tempered_glass"))))
                    .where("d", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:solid_machine_casing"))))
                    .where("e", Predicates.blocks(ForgeRegistries.BLOCKS.getValue(ResourceLocation.parse("gtceu:bronze_pipe_casing"))))
                    .where('i', Predicates.controller(Predicates.blocks(definition.get())))
                    .build()
            )
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Abilities: Perfect Overclock, Parallel Hatch and Threading").withStyle(style -> style.withColor(0xFFD700)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Created for ultra-fast brewing.").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("----------------------------------------").withStyle(s -> s.withColor(0xff0000)))
            .tooltips(Component.literal("Available Recipe Types: Brewery, Fermenter, Fluid Heater").withStyle(style -> style.withColor(0x90EE90)))
            .tooltips(Component.literal("Accepts Threading Core T3.").withStyle(ChatFormatting.LIGHT_PURPLE))
            .workableCasingModel(
                    GTCEu.id("block/casings/gcym/corrosion_proof_casing"),
                    GTCEu.id("block/multiblock/distillation_tower")
            )
            .register();

    public static final MachineDefinition[] ALL_MACHINES = {
            GIANT_CRYSTALLIZATION, GIANT_EXTRACTION, GIANT_SOLIDIFICATION, GIANT_CHEMICAL_BATH, GIANT_DISTILLATION, GIANT_EXTRUSION_MACHINE, GIANT_MATERIAL_PRESS, GIANT_SOLIDIFICATION,
            GIANT_WIRE_FACTORY, GIANT_ASSEMBLER_CIRCUIT, GIANT_ASSEMBLER, GIANT_SIFTER, GIANT_CENTRIFUGE, GIANT_ELECTROMAGNET, GIANT_ELECTROLYZER, GIANT_MACERATOR, GIANT_MIXER,
            GIANT_ENGRAVER, GIANT_SAW, GIANT_ARC_FURNACE, GIANT_BREWERY
    };

    public static void init(){}
}
